name        = "Propergol"
name8       = "ppg"
locale      = "fr"
variant     = "Kawa"
author      = "Kawamashi"
description = "French Ergo"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "0.0.6"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ |   │ <   │ > ⅔ │ $ ¾ │ %   ┃ ^ ‚ │ & ‘ │ _ ’ │ #   │ @   ┃ * × ┆ \ ≠ ┆
┆ `   ┃ 1 ¢ │ 2 ½ │ 3 ⅓ │ 4 ¼ │ 5 ¶ ┃ 6 ™ │ 7 © │ 8 ∞ │ 9 ° │ 0 § ┃ / ÷ ┆ = ≈ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ ?   │ É   │ U   │ P   │ B   ┃ V „ │ M “ │ C ” │ ! ¡ │ X   ┃ "   ┆ + ± ┆
·     ┃ . ô │   â │   î │   û │   @ ┃   " │   « │   » │ ’ • │   · ┃ '   ┆ - − ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ O   │ A   │ I   │ N   │ : ¿ ┃ G   │ T ‑ │ S — │ R   │ L   ┃ -   ┆ ?   ┆
·     ┃   ê │   à │   ï │   ù │ , … ┃  *µ │   - │   – │   € │   £ ┃ [ { ┆ ] } ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ E   ┃ Q   │ Z   │ Y   │ H   │ J   ┃ K   │ D   │ F   │ W   │ ;   ┃           ·
┆   è ┃   œ │   æ │  *¨ │   ñ │   ( ┃   ) │   ç │   ß │   _ │**   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆   … ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │  *˘ │  *˚ │  *¤ │     ┃   ‰ │  *” │   ≠ │   ¬ │  *` ┃     ┆     ┆
·     ┃   ^ │   { │   } │   $ │   # ┃   % │   " │   = │   ! │   ` ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │     │     │  *˙ │   : ┃  */ │   ÷ │  *¯ │   ± │   × ┃     ┆     ┆
·     ┃   ? │   ( │   ) │   ; │   : ┃   \ │   / │   - │   + │   * ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   ≤ │  *, │  *˛ │   ≥ │     ┃     │  *´ │  *¸ │   ¦ │  *~ ┃           ·
┆   _ ┃   < │   [ │   ] │   > │   @ ┃     │   ' │   & │   | │   ~ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u002d"  # HYPHEN-MINUS
1dk_shift   = "\u2011"  # NON-BREAKING HYPHEN
