name        = "Propergol"
name8       = "ppg"
locale      = "fr"
variant     = "propergol"
author      = "Kawamashi"
description = "French Ergo"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "0.0.2"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ Ç   ┃ 1   │ «   │ »   │ 4   │ 5   ┃ 6 ‚ │ 7 ‘ │ 8 ’ │ 9   │ …   ┃ /   ┆ *   ┆
┆     ┃   ™ │ 2 ∞ │ 3 ß │   § │   © ┃   ¶ │   £ │   ñ │   ° │ 0 € ┃   ÷ ┆   × ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ ?   │ É   │ U   │ P   │ B   ┃ F „ │ M “ │ C ” │ ! ¡ │ X   ┃ ≠ ≠ ┆ +   ┆
·     ┃ . ô │   â │   î │   û │   µ ┃   " │   « │   » │ ’ • │   · ┃ = ≈ ┆   ± ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ O   │ A   │ I   │ N   │ : ¿ ┃ V   │ T ‑ │ S   │ R   │ L   ┃ -   ┆ ? ¿ ┆
·     ┃   ê │   à │   ñ │   ù │ , … ┃   ß │   - │   ç │   ( │   ) ┃   − ┆ ' • ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ E   ┃ Q   │ Z   │ Y   │ H   │ J   ┃ K   │ D — │ G   │ W _ │ ;   ┃           ·
┆   è ┃   œ │   æ │   ï │  *¨ │   @ ┃   € │   – │  *µ │   _ │**   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃   à ┆   ê ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │  *˘ │  *˚ │  *¤ │     ┃   ‰ │  *” │   ≠ │   ¬ │  *´ ┃     ┆     ┆
·     ┃   ^ │   { │   } │   $ │   # ┃   % │   " │   = │   ! │   ' ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │     │     │  *˙ │   : ┃  */ │   ÷ │  *¯ │   ± │   × ┃     ┆     ┆
·     ┃   ? │   ( │   ) │   ; │   : ┃   \ │   / │   - │   + │   * ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   ≤ │  *, │  *˛ │   ≥ │     ┃     │  *` │  *¸ │   ¦ │  *~ ┃           ·
┆   _ ┃   < │   [ │   ] │   > │   @ ┃     │   ` │   & │   | │   ~ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u002d"  # HYPHEN-MINUS
1dk_shift   = "\u002d"  # HYPHEN-MINUS
